# Generated by Django 3.2.5 on 2021-07-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210724_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='option',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='name',
        ),
        migrations.AddField(
            model_name='variants',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
    ]
